development: &default
  adapter: mysql
  database: dddd_development
  username: root
  password:
  host: localhost
  encoding: utf8

test: &test
  <<: *default
  database: dddd_test

cucumber:
  <<: *test
